---

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: "clickhouse-event-exporter"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "clickhouse-event-exporter"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "clickhouse-event-exporter"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: "clickhouse-event-exporter"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          env:
            {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: "http"
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: "http"
            initialDelaySeconds: 5
            periodSeconds: 10
